### ISSUE TITLE
Tag New Release

### ISSUE THREAD

**Issue by johnnygreen** [comandeo/crystal-memcached#20]
First off, thank you @comandeo for this library.  I'm new to Crystal and it's been very helpful to have all these nice, free shards to install.

I see someone fixed the issue I've been having the last few days back in January with this commit, 7049e6d487ea3af55800d32b1f4034472e31a341, but it's not been tagged in an official release.  

Should I just change my branch to master or is there a plan to incorporate this patch in a future tagged release?

Thank you.

**Comment by comandeo** [comment]
Hi Johnny,

Thank you very much for the feedback and sorry for the delay with the response. The latest code has been tagged, and the version bumped.

**Comment by johnnygreen** [comment]
Thank you!
